// ponytail: plain Node script, no build step / no new dependency — run with `node scripts/import-quran.mjs`.
// One-time import of all 114 surahs + ayahs from EQuran.id into a seed SQL file for D1.
import { writeFile } from "node:fs/promises";

const EQURAN_BASE = "https://equran.id/api/v2";
const OUT_FILE = new URL("../seeds/quran-full.sql", import.meta.url);

const escapeSql = (value) => `'${String(value).replace(/'/g, "''")}'`;
const audioUrl = (surahId, ayahNumber) =>
  `https://cdn.equran.id/audio-partial/Misyari-Rasyid-Al-Afasi/${String(surahId).padStart(3, "0")}${String(ayahNumber).padStart(3, "0")}.mp3`;

async function fetchSurah(id) {
  const res = await fetch(`${EQURAN_BASE}/surat/${id}`, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error(`Surah ${id}: HTTP ${res.status}`);
  const body = await res.json();
  return body.data;
}

async function main() {
  const surahLines = [];
  const ayahLines = [];

  for (let id = 1; id <= 114; id++) {
    let data;
    for (let attempt = 1; attempt <= 2 && !data; attempt++) {
      try {
        data = await fetchSurah(id);
      } catch (err) {
        console.error(`Gagal mengambil surah ${id} (percobaan ${attempt}):`, err.message);
        if (attempt === 2) throw err;
        await new Promise(r => setTimeout(r, 500));
      }
    }

    surahLines.push(
      `INSERT OR IGNORE INTO surahs (id, latin_name, arabic_name, meaning, ayah_count) VALUES (${data.nomor}, ${escapeSql(data.namaLatin)}, ${escapeSql(data.nama)}, ${escapeSql(data.arti)}, ${data.jumlahAyat});`,
    );
    for (const ayah of data.ayat) {
      ayahLines.push(
        `INSERT OR IGNORE INTO ayahs (surah_id, number, arabic, transliteration, translation, audio_url) VALUES (${data.nomor}, ${ayah.nomorAyat}, ${escapeSql(ayah.teksArab)}, ${escapeSql(ayah.teksLatin)}, ${escapeSql(ayah.teksIndonesia)}, ${escapeSql(audioUrl(data.nomor, ayah.nomorAyat))});`,
      );
    }
    console.log(`Surah ${id}/114 (${data.namaLatin}) siap diimpor`);
    await new Promise(r => setTimeout(r, 150)); // be polite to the API
  }

  const sql = [
    "-- Generated by packages/db/scripts/import-quran.mjs — do not edit by hand.",
    ...surahLines,
    ...ayahLines,
    "",
  ].join("\n");

  await writeFile(OUT_FILE, sql, "utf8");
  console.log(`\nSelesai. Ditulis ke ${OUT_FILE.pathname}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
